// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Krokozabra213/e-commerce_shop/services/inventory-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
	isgomock struct{}
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStockRepository) Create(ctx context.Context, stock *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStockRepositoryMockRecorder) Create(ctx, stock any) *MockStockRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStockRepository)(nil).Create), ctx, stock)
	return &MockStockRepositoryCreateCall{Call: call}
}

// MockStockRepositoryCreateCall wrap *gomock.Call
type MockStockRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockRepositoryCreateCall) Return(arg0 error) *MockStockRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockRepositoryCreateCall) Do(f func(context.Context, *domain.Stock) error) *MockStockRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.Stock) error) *MockStockRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByProductID mocks base method.
func (m *MockStockRepository) GetByProductID(ctx context.Context, productID string) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductID", ctx, productID)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductID indicates an expected call of GetByProductID.
func (mr *MockStockRepositoryMockRecorder) GetByProductID(ctx, productID any) *MockStockRepositoryGetByProductIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductID", reflect.TypeOf((*MockStockRepository)(nil).GetByProductID), ctx, productID)
	return &MockStockRepositoryGetByProductIDCall{Call: call}
}

// MockStockRepositoryGetByProductIDCall wrap *gomock.Call
type MockStockRepositoryGetByProductIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockRepositoryGetByProductIDCall) Return(arg0 *domain.Stock, arg1 error) *MockStockRepositoryGetByProductIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockRepositoryGetByProductIDCall) Do(f func(context.Context, string) (*domain.Stock, error)) *MockStockRepositoryGetByProductIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockRepositoryGetByProductIDCall) DoAndReturn(f func(context.Context, string) (*domain.Stock, error)) *MockStockRepositoryGetByProductIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByProductIDs mocks base method.
func (m *MockStockRepository) GetByProductIDs(ctx context.Context, productIDs []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductIDs", ctx, productIDs)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductIDs indicates an expected call of GetByProductIDs.
func (mr *MockStockRepositoryMockRecorder) GetByProductIDs(ctx, productIDs any) *MockStockRepositoryGetByProductIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductIDs", reflect.TypeOf((*MockStockRepository)(nil).GetByProductIDs), ctx, productIDs)
	return &MockStockRepositoryGetByProductIDsCall{Call: call}
}

// MockStockRepositoryGetByProductIDsCall wrap *gomock.Call
type MockStockRepositoryGetByProductIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockRepositoryGetByProductIDsCall) Return(arg0 map[string]int, arg1 error) *MockStockRepositoryGetByProductIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockRepositoryGetByProductIDsCall) Do(f func(context.Context, []string) (map[string]int, error)) *MockStockRepositoryGetByProductIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockRepositoryGetByProductIDsCall) DoAndReturn(f func(context.Context, []string) (map[string]int, error)) *MockStockRepositoryGetByProductIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncreaseQuantity mocks base method.
func (m *MockStockRepository) IncreaseQuantity(ctx context.Context, productID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseQuantity", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseQuantity indicates an expected call of IncreaseQuantity.
func (mr *MockStockRepositoryMockRecorder) IncreaseQuantity(ctx, productID, quantity any) *MockStockRepositoryIncreaseQuantityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseQuantity", reflect.TypeOf((*MockStockRepository)(nil).IncreaseQuantity), ctx, productID, quantity)
	return &MockStockRepositoryIncreaseQuantityCall{Call: call}
}

// MockStockRepositoryIncreaseQuantityCall wrap *gomock.Call
type MockStockRepositoryIncreaseQuantityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockRepositoryIncreaseQuantityCall) Return(arg0 error) *MockStockRepositoryIncreaseQuantityCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockRepositoryIncreaseQuantityCall) Do(f func(context.Context, string, int) error) *MockStockRepositoryIncreaseQuantityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockRepositoryIncreaseQuantityCall) DoAndReturn(f func(context.Context, string, int) error) *MockStockRepositoryIncreaseQuantityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event *domain.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *MockOutboxRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
	return &MockOutboxRepositoryCreateCall{Call: call}
}

// MockOutboxRepositoryCreateCall wrap *gomock.Call
type MockOutboxRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOutboxRepositoryCreateCall) Return(arg0 error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOutboxRepositoryCreateCall) Do(f func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOutboxRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTxManager) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTxManagerMockRecorder) WithinTransaction(ctx, fn any) *MockTxManagerWithinTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTxManager)(nil).WithinTransaction), ctx, fn)
	return &MockTxManagerWithinTransactionCall{Call: call}
}

// MockTxManagerWithinTransactionCall wrap *gomock.Call
type MockTxManagerWithinTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxManagerWithinTransactionCall) Return(arg0 error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxManagerWithinTransactionCall) Do(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxManagerWithinTransactionCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
