version: "2"
run:
  modules-download-mode: readonly


linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _test\.go
      - vendor
      - api

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra:
        group-params: true
  exclusions:
    generated: lax
    paths:
      - vendor
      - api




#linters:
#  enable:
#    - revive
#  settings:
#    gocyclo:
#      min-complexity: 15
#  exclusions:
#    generated: lax
#    presets:
#      - comments
#      - common-false-positives
#      - legacy
#      - std-error-handling
#    paths:
#      - _test\.go
#      - vendor
#      - api