run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - api

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gofumpt
    - misspell
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  gofumpt:
    extra-rules: true