// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Krokozabra213/e-commerce_shop/services/inventory-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
	isgomock struct{}
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// DecreaseQuantity mocks base method.
func (m *MockStockRepository) DecreaseQuantity(ctx context.Context, productID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseQuantity", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseQuantity indicates an expected call of DecreaseQuantity.
func (mr *MockStockRepositoryMockRecorder) DecreaseQuantity(ctx, productID, quantity any) *MockStockRepositoryDecreaseQuantityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseQuantity", reflect.TypeOf((*MockStockRepository)(nil).DecreaseQuantity), ctx, productID, quantity)
	return &MockStockRepositoryDecreaseQuantityCall{Call: call}
}

// MockStockRepositoryDecreaseQuantityCall wrap *gomock.Call
type MockStockRepositoryDecreaseQuantityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockRepositoryDecreaseQuantityCall) Return(arg0 error) *MockStockRepositoryDecreaseQuantityCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockRepositoryDecreaseQuantityCall) Do(f func(context.Context, string, int) error) *MockStockRepositoryDecreaseQuantityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockRepositoryDecreaseQuantityCall) DoAndReturn(f func(context.Context, string, int) error) *MockStockRepositoryDecreaseQuantityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncreaseQuantity mocks base method.
func (m *MockStockRepository) IncreaseQuantity(ctx context.Context, productID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseQuantity", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseQuantity indicates an expected call of IncreaseQuantity.
func (mr *MockStockRepositoryMockRecorder) IncreaseQuantity(ctx, productID, quantity any) *MockStockRepositoryIncreaseQuantityCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseQuantity", reflect.TypeOf((*MockStockRepository)(nil).IncreaseQuantity), ctx, productID, quantity)
	return &MockStockRepositoryIncreaseQuantityCall{Call: call}
}

// MockStockRepositoryIncreaseQuantityCall wrap *gomock.Call
type MockStockRepositoryIncreaseQuantityCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockRepositoryIncreaseQuantityCall) Return(arg0 error) *MockStockRepositoryIncreaseQuantityCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockRepositoryIncreaseQuantityCall) Do(f func(context.Context, string, int) error) *MockStockRepositoryIncreaseQuantityCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockRepositoryIncreaseQuantityCall) DoAndReturn(f func(context.Context, string, int) error) *MockStockRepositoryIncreaseQuantityCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockReservationRepository) CreateBatch(ctx context.Context, reservations []*domain.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, reservations)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockReservationRepositoryMockRecorder) CreateBatch(ctx, reservations any) *MockReservationRepositoryCreateBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockReservationRepository)(nil).CreateBatch), ctx, reservations)
	return &MockReservationRepositoryCreateBatchCall{Call: call}
}

// MockReservationRepositoryCreateBatchCall wrap *gomock.Call
type MockReservationRepositoryCreateBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationRepositoryCreateBatchCall) Return(arg0 error) *MockReservationRepositoryCreateBatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationRepositoryCreateBatchCall) Do(f func(context.Context, []*domain.Reservation) error) *MockReservationRepositoryCreateBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationRepositoryCreateBatchCall) DoAndReturn(f func(context.Context, []*domain.Reservation) error) *MockReservationRepositoryCreateBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExistsByOrderID mocks base method.
func (m *MockReservationRepository) ExistsByOrderID(ctx context.Context, orderID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByOrderID", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByOrderID indicates an expected call of ExistsByOrderID.
func (mr *MockReservationRepositoryMockRecorder) ExistsByOrderID(ctx, orderID any) *MockReservationRepositoryExistsByOrderIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByOrderID", reflect.TypeOf((*MockReservationRepository)(nil).ExistsByOrderID), ctx, orderID)
	return &MockReservationRepositoryExistsByOrderIDCall{Call: call}
}

// MockReservationRepositoryExistsByOrderIDCall wrap *gomock.Call
type MockReservationRepositoryExistsByOrderIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationRepositoryExistsByOrderIDCall) Return(arg0 bool, arg1 error) *MockReservationRepositoryExistsByOrderIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationRepositoryExistsByOrderIDCall) Do(f func(context.Context, uuid.UUID) (bool, error)) *MockReservationRepositoryExistsByOrderIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationRepositoryExistsByOrderIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (bool, error)) *MockReservationRepositoryExistsByOrderIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActiveByOrderID mocks base method.
func (m *MockReservationRepository) GetActiveByOrderID(ctx context.Context, orderID uuid.UUID) ([]*domain.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]*domain.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByOrderID indicates an expected call of GetActiveByOrderID.
func (mr *MockReservationRepositoryMockRecorder) GetActiveByOrderID(ctx, orderID any) *MockReservationRepositoryGetActiveByOrderIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByOrderID", reflect.TypeOf((*MockReservationRepository)(nil).GetActiveByOrderID), ctx, orderID)
	return &MockReservationRepositoryGetActiveByOrderIDCall{Call: call}
}

// MockReservationRepositoryGetActiveByOrderIDCall wrap *gomock.Call
type MockReservationRepositoryGetActiveByOrderIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationRepositoryGetActiveByOrderIDCall) Return(arg0 []*domain.Reservation, arg1 error) *MockReservationRepositoryGetActiveByOrderIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationRepositoryGetActiveByOrderIDCall) Do(f func(context.Context, uuid.UUID) ([]*domain.Reservation, error)) *MockReservationRepositoryGetActiveByOrderIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationRepositoryGetActiveByOrderIDCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]*domain.Reservation, error)) *MockReservationRepositoryGetActiveByOrderIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReleaseByOrderID mocks base method.
func (m *MockReservationRepository) ReleaseByOrderID(ctx context.Context, orderID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseByOrderID", ctx, orderID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseByOrderID indicates an expected call of ReleaseByOrderID.
func (mr *MockReservationRepositoryMockRecorder) ReleaseByOrderID(ctx, orderID any) *MockReservationRepositoryReleaseByOrderIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseByOrderID", reflect.TypeOf((*MockReservationRepository)(nil).ReleaseByOrderID), ctx, orderID)
	return &MockReservationRepositoryReleaseByOrderIDCall{Call: call}
}

// MockReservationRepositoryReleaseByOrderIDCall wrap *gomock.Call
type MockReservationRepositoryReleaseByOrderIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReservationRepositoryReleaseByOrderIDCall) Return(arg0 int, arg1 error) *MockReservationRepositoryReleaseByOrderIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReservationRepositoryReleaseByOrderIDCall) Do(f func(context.Context, uuid.UUID) (int, error)) *MockReservationRepositoryReleaseByOrderIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReservationRepositoryReleaseByOrderIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (int, error)) *MockReservationRepositoryReleaseByOrderIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event *domain.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *MockOutboxRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
	return &MockOutboxRepositoryCreateCall{Call: call}
}

// MockOutboxRepositoryCreateCall wrap *gomock.Call
type MockOutboxRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOutboxRepositoryCreateCall) Return(arg0 error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOutboxRepositoryCreateCall) Do(f func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOutboxRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAdvisoryLocker is a mock of AdvisoryLocker interface.
type MockAdvisoryLocker struct {
	ctrl     *gomock.Controller
	recorder *MockAdvisoryLockerMockRecorder
	isgomock struct{}
}

// MockAdvisoryLockerMockRecorder is the mock recorder for MockAdvisoryLocker.
type MockAdvisoryLockerMockRecorder struct {
	mock *MockAdvisoryLocker
}

// NewMockAdvisoryLocker creates a new mock instance.
func NewMockAdvisoryLocker(ctrl *gomock.Controller) *MockAdvisoryLocker {
	mock := &MockAdvisoryLocker{ctrl: ctrl}
	mock.recorder = &MockAdvisoryLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvisoryLocker) EXPECT() *MockAdvisoryLockerMockRecorder {
	return m.recorder
}

// LockByUUID mocks base method.
func (m *MockAdvisoryLocker) LockByUUID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByUUID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockByUUID indicates an expected call of LockByUUID.
func (mr *MockAdvisoryLockerMockRecorder) LockByUUID(ctx, id any) *MockAdvisoryLockerLockByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByUUID", reflect.TypeOf((*MockAdvisoryLocker)(nil).LockByUUID), ctx, id)
	return &MockAdvisoryLockerLockByUUIDCall{Call: call}
}

// MockAdvisoryLockerLockByUUIDCall wrap *gomock.Call
type MockAdvisoryLockerLockByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdvisoryLockerLockByUUIDCall) Return(arg0 error) *MockAdvisoryLockerLockByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdvisoryLockerLockByUUIDCall) Do(f func(context.Context, uuid.UUID) error) *MockAdvisoryLockerLockByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdvisoryLockerLockByUUIDCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockAdvisoryLockerLockByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTxManager) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTxManagerMockRecorder) WithinTransaction(ctx, fn any) *MockTxManagerWithinTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTxManager)(nil).WithinTransaction), ctx, fn)
	return &MockTxManagerWithinTransactionCall{Call: call}
}

// MockTxManagerWithinTransactionCall wrap *gomock.Call
type MockTxManagerWithinTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxManagerWithinTransactionCall) Return(arg0 error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxManagerWithinTransactionCall) Do(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxManagerWithinTransactionCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
