// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	manager "github.com/Krokozabra213/e-commerce_shop/infra/jwt/manager"
	domain "github.com/Krokozabra213/e-commerce_shop/services/auth-service/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ConfirmEmail mocks base method.
func (m *MockUserRepository) ConfirmEmail(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmEmail", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmEmail indicates an expected call of ConfirmEmail.
func (mr *MockUserRepositoryMockRecorder) ConfirmEmail(ctx, userID any) *MockUserRepositoryConfirmEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmail", reflect.TypeOf((*MockUserRepository)(nil).ConfirmEmail), ctx, userID)
	return &MockUserRepositoryConfirmEmailCall{Call: call}
}

// MockUserRepositoryConfirmEmailCall wrap *gomock.Call
type MockUserRepositoryConfirmEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryConfirmEmailCall) Return(arg0 error) *MockUserRepositoryConfirmEmailCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryConfirmEmailCall) Do(f func(context.Context, uuid.UUID) error) *MockUserRepositoryConfirmEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryConfirmEmailCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockUserRepositoryConfirmEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *MockUserRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
	return &MockUserRepositoryCreateCall{Call: call}
}

// MockUserRepositoryCreateCall wrap *gomock.Call
type MockUserRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCreateCall) Return(arg0 error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCreateCall) Do(f func(context.Context, *domain.User) error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.User) error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *MockUserRepositoryGetByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
	return &MockUserRepositoryGetByEmailCall{Call: call}
}

// MockUserRepositoryGetByEmailCall wrap *gomock.Call
type MockUserRepositoryGetByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetByEmailCall) Return(arg0 *domain.User, arg1 error) *MockUserRepositoryGetByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetByEmailCall) Do(f func(context.Context, string) (*domain.User, error)) *MockUserRepositoryGetByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetByEmailCall) DoAndReturn(f func(context.Context, string) (*domain.User, error)) *MockUserRepositoryGetByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *MockUserRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
	return &MockUserRepositoryGetByIDCall{Call: call}
}

// MockUserRepositoryGetByIDCall wrap *gomock.Call
type MockUserRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetByIDCall) Return(arg0 *domain.User, arg1 error) *MockUserRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetByIDCall) Do(f func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetByIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token *domain.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *MockRefreshTokenRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
	return &MockRefreshTokenRepositoryCreateCall{Call: call}
}

// MockRefreshTokenRepositoryCreateCall wrap *gomock.Call
type MockRefreshTokenRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryCreateCall) Return(arg0 error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryCreateCall) Do(f func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByTokenHashForUpdate mocks base method.
func (m *MockRefreshTokenRepository) GetByTokenHashForUpdate(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHashForUpdate", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHashForUpdate indicates an expected call of GetByTokenHashForUpdate.
func (mr *MockRefreshTokenRepositoryMockRecorder) GetByTokenHashForUpdate(ctx, tokenHash any) *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHashForUpdate", reflect.TypeOf((*MockRefreshTokenRepository)(nil).GetByTokenHashForUpdate), ctx, tokenHash)
	return &MockRefreshTokenRepositoryGetByTokenHashForUpdateCall{Call: call}
}

// MockRefreshTokenRepositoryGetByTokenHashForUpdateCall wrap *gomock.Call
type MockRefreshTokenRepositoryGetByTokenHashForUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall) Return(arg0 *domain.RefreshToken, arg1 error) *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall) Do(f func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall) DoAndReturn(f func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepositoryGetByTokenHashForUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MockRefreshTokenRepository) Revoke(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenRepositoryMockRecorder) Revoke(ctx, tokenHash any) *MockRefreshTokenRepositoryRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Revoke), ctx, tokenHash)
	return &MockRefreshTokenRepositoryRevokeCall{Call: call}
}

// MockRefreshTokenRepositoryRevokeCall wrap *gomock.Call
type MockRefreshTokenRepositoryRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRefreshTokenRepositoryRevokeCall) Return(arg0 error) *MockRefreshTokenRepositoryRevokeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRefreshTokenRepositoryRevokeCall) Do(f func(context.Context, string) error) *MockRefreshTokenRepositoryRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRefreshTokenRepositoryRevokeCall) DoAndReturn(f func(context.Context, string) error) *MockRefreshTokenRepositoryRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEmailVerificationRepository is a mock of EmailVerificationRepository interface.
type MockEmailVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailVerificationRepositoryMockRecorder is the mock recorder for MockEmailVerificationRepository.
type MockEmailVerificationRepositoryMockRecorder struct {
	mock *MockEmailVerificationRepository
}

// NewMockEmailVerificationRepository creates a new mock instance.
func NewMockEmailVerificationRepository(ctrl *gomock.Controller) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailVerificationRepository) Create(ctx context.Context, token *domain.EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationRepositoryMockRecorder) Create(ctx, token any) *MockEmailVerificationRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationRepository)(nil).Create), ctx, token)
	return &MockEmailVerificationRepositoryCreateCall{Call: call}
}

// MockEmailVerificationRepositoryCreateCall wrap *gomock.Call
type MockEmailVerificationRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailVerificationRepositoryCreateCall) Return(arg0 error) *MockEmailVerificationRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailVerificationRepositoryCreateCall) Do(f func(context.Context, *domain.EmailVerificationToken) error) *MockEmailVerificationRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailVerificationRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.EmailVerificationToken) error) *MockEmailVerificationRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByTokenHashForUpdate mocks base method.
func (m *MockEmailVerificationRepository) GetByTokenHashForUpdate(ctx context.Context, tokenHash string) (*domain.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHashForUpdate", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHashForUpdate indicates an expected call of GetByTokenHashForUpdate.
func (mr *MockEmailVerificationRepositoryMockRecorder) GetByTokenHashForUpdate(ctx, tokenHash any) *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHashForUpdate", reflect.TypeOf((*MockEmailVerificationRepository)(nil).GetByTokenHashForUpdate), ctx, tokenHash)
	return &MockEmailVerificationRepositoryGetByTokenHashForUpdateCall{Call: call}
}

// MockEmailVerificationRepositoryGetByTokenHashForUpdateCall wrap *gomock.Call
type MockEmailVerificationRepositoryGetByTokenHashForUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall) Return(arg0 *domain.EmailVerificationToken, arg1 error) *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall) Do(f func(context.Context, string) (*domain.EmailVerificationToken, error)) *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall) DoAndReturn(f func(context.Context, string) (*domain.EmailVerificationToken, error)) *MockEmailVerificationRepositoryGetByTokenHashForUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkAsUsed mocks base method.
func (m *MockEmailVerificationRepository) MarkAsUsed(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockEmailVerificationRepositoryMockRecorder) MarkAsUsed(ctx, tokenHash any) *MockEmailVerificationRepositoryMarkAsUsedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockEmailVerificationRepository)(nil).MarkAsUsed), ctx, tokenHash)
	return &MockEmailVerificationRepositoryMarkAsUsedCall{Call: call}
}

// MockEmailVerificationRepositoryMarkAsUsedCall wrap *gomock.Call
type MockEmailVerificationRepositoryMarkAsUsedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEmailVerificationRepositoryMarkAsUsedCall) Return(arg0 error) *MockEmailVerificationRepositoryMarkAsUsedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEmailVerificationRepositoryMarkAsUsedCall) Do(f func(context.Context, string) error) *MockEmailVerificationRepositoryMarkAsUsedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEmailVerificationRepositoryMarkAsUsedCall) DoAndReturn(f func(context.Context, string) error) *MockEmailVerificationRepositoryMarkAsUsedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event *domain.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *MockOutboxRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
	return &MockOutboxRepositoryCreateCall{Call: call}
}

// MockOutboxRepositoryCreateCall wrap *gomock.Call
type MockOutboxRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOutboxRepositoryCreateCall) Return(arg0 error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOutboxRepositoryCreateCall) Do(f func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOutboxRepositoryCreateCall) DoAndReturn(f func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockJWTManager is a mock of JWTManager interface.
type MockJWTManager struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerMockRecorder
	isgomock struct{}
}

// MockJWTManagerMockRecorder is the mock recorder for MockJWTManager.
type MockJWTManagerMockRecorder struct {
	mock *MockJWTManager
}

// NewMockJWTManager creates a new mock instance.
func NewMockJWTManager(ctrl *gomock.Controller) *MockJWTManager {
	mock := &MockJWTManager{ctrl: ctrl}
	mock.recorder = &MockJWTManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManager) EXPECT() *MockJWTManagerMockRecorder {
	return m.recorder
}

// GenerateTokens mocks base method.
func (m *MockJWTManager) GenerateTokens(userID uuid.UUID) (string, string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockJWTManagerMockRecorder) GenerateTokens(userID any) *MockJWTManagerGenerateTokensCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*MockJWTManager)(nil).GenerateTokens), userID)
	return &MockJWTManagerGenerateTokensCall{Call: call}
}

// MockJWTManagerGenerateTokensCall wrap *gomock.Call
type MockJWTManagerGenerateTokensCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJWTManagerGenerateTokensCall) Return(access, refresh string, refreshExp time.Time, err error) *MockJWTManagerGenerateTokensCall {
	c.Call = c.Call.Return(access, refresh, refreshExp, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJWTManagerGenerateTokensCall) Do(f func(uuid.UUID) (string, string, time.Time, error)) *MockJWTManagerGenerateTokensCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJWTManagerGenerateTokensCall) DoAndReturn(f func(uuid.UUID) (string, string, time.Time, error)) *MockJWTManagerGenerateTokensCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockJWTValidator is a mock of JWTValidator interface.
type MockJWTValidator struct {
	ctrl     *gomock.Controller
	recorder *MockJWTValidatorMockRecorder
	isgomock struct{}
}

// MockJWTValidatorMockRecorder is the mock recorder for MockJWTValidator.
type MockJWTValidatorMockRecorder struct {
	mock *MockJWTValidator
}

// NewMockJWTValidator creates a new mock instance.
func NewMockJWTValidator(ctrl *gomock.Controller) *MockJWTValidator {
	mock := &MockJWTValidator{ctrl: ctrl}
	mock.recorder = &MockJWTValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTValidator) EXPECT() *MockJWTValidatorMockRecorder {
	return m.recorder
}

// ValidateAccess mocks base method.
func (m *MockJWTValidator) ValidateAccess(tokenString string) (*manager.AccessClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccess", tokenString)
	ret0, _ := ret[0].(*manager.AccessClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccess indicates an expected call of ValidateAccess.
func (mr *MockJWTValidatorMockRecorder) ValidateAccess(tokenString any) *MockJWTValidatorValidateAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccess", reflect.TypeOf((*MockJWTValidator)(nil).ValidateAccess), tokenString)
	return &MockJWTValidatorValidateAccessCall{Call: call}
}

// MockJWTValidatorValidateAccessCall wrap *gomock.Call
type MockJWTValidatorValidateAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJWTValidatorValidateAccessCall) Return(arg0 *manager.AccessClaims, arg1 error) *MockJWTValidatorValidateAccessCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJWTValidatorValidateAccessCall) Do(f func(string) (*manager.AccessClaims, error)) *MockJWTValidatorValidateAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJWTValidatorValidateAccessCall) DoAndReturn(f func(string) (*manager.AccessClaims, error)) *MockJWTValidatorValidateAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateRefresh mocks base method.
func (m *MockJWTValidator) ValidateRefresh(tokenString string) (*manager.RefreshClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefresh", tokenString)
	ret0, _ := ret[0].(*manager.RefreshClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefresh indicates an expected call of ValidateRefresh.
func (mr *MockJWTValidatorMockRecorder) ValidateRefresh(tokenString any) *MockJWTValidatorValidateRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefresh", reflect.TypeOf((*MockJWTValidator)(nil).ValidateRefresh), tokenString)
	return &MockJWTValidatorValidateRefreshCall{Call: call}
}

// MockJWTValidatorValidateRefreshCall wrap *gomock.Call
type MockJWTValidatorValidateRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJWTValidatorValidateRefreshCall) Return(arg0 *manager.RefreshClaims, arg1 error) *MockJWTValidatorValidateRefreshCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJWTValidatorValidateRefreshCall) Do(f func(string) (*manager.RefreshClaims, error)) *MockJWTValidatorValidateRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJWTValidatorValidateRefreshCall) DoAndReturn(f func(string) (*manager.RefreshClaims, error)) *MockJWTValidatorValidateRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockJWTKeyStore is a mock of JWTKeyStore interface.
type MockJWTKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockJWTKeyStoreMockRecorder
	isgomock struct{}
}

// MockJWTKeyStoreMockRecorder is the mock recorder for MockJWTKeyStore.
type MockJWTKeyStoreMockRecorder struct {
	mock *MockJWTKeyStore
}

// NewMockJWTKeyStore creates a new mock instance.
func NewMockJWTKeyStore(ctrl *gomock.Controller) *MockJWTKeyStore {
	mock := &MockJWTKeyStore{ctrl: ctrl}
	mock.recorder = &MockJWTKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTKeyStore) EXPECT() *MockJWTKeyStoreMockRecorder {
	return m.recorder
}

// GetPublicKeyPEM mocks base method.
func (m *MockJWTKeyStore) GetPublicKeyPEM() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKeyPEM")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKeyPEM indicates an expected call of GetPublicKeyPEM.
func (mr *MockJWTKeyStoreMockRecorder) GetPublicKeyPEM() *MockJWTKeyStoreGetPublicKeyPEMCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKeyPEM", reflect.TypeOf((*MockJWTKeyStore)(nil).GetPublicKeyPEM))
	return &MockJWTKeyStoreGetPublicKeyPEMCall{Call: call}
}

// MockJWTKeyStoreGetPublicKeyPEMCall wrap *gomock.Call
type MockJWTKeyStoreGetPublicKeyPEMCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJWTKeyStoreGetPublicKeyPEMCall) Return(arg0 string, arg1 error) *MockJWTKeyStoreGetPublicKeyPEMCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJWTKeyStoreGetPublicKeyPEMCall) Do(f func() (string, error)) *MockJWTKeyStoreGetPublicKeyPEMCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJWTKeyStoreGetPublicKeyPEMCall) DoAndReturn(f func() (string, error)) *MockJWTKeyStoreGetPublicKeyPEMCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPassHasher is a mock of PassHasher interface.
type MockPassHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPassHasherMockRecorder
	isgomock struct{}
}

// MockPassHasherMockRecorder is the mock recorder for MockPassHasher.
type MockPassHasherMockRecorder struct {
	mock *MockPassHasher
}

// NewMockPassHasher creates a new mock instance.
func NewMockPassHasher(ctrl *gomock.Controller) *MockPassHasher {
	mock := &MockPassHasher{ctrl: ctrl}
	mock.recorder = &MockPassHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPassHasher) EXPECT() *MockPassHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockPassHasher) Compare(password, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", password, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockPassHasherMockRecorder) Compare(password, hash any) *MockPassHasherCompareCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockPassHasher)(nil).Compare), password, hash)
	return &MockPassHasherCompareCall{Call: call}
}

// MockPassHasherCompareCall wrap *gomock.Call
type MockPassHasherCompareCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPassHasherCompareCall) Return(arg0 bool, arg1 error) *MockPassHasherCompareCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPassHasherCompareCall) Do(f func(string, string) (bool, error)) *MockPassHasherCompareCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPassHasherCompareCall) DoAndReturn(f func(string, string) (bool, error)) *MockPassHasherCompareCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Hash mocks base method.
func (m *MockPassHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPassHasherMockRecorder) Hash(password any) *MockPassHasherHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPassHasher)(nil).Hash), password)
	return &MockPassHasherHashCall{Call: call}
}

// MockPassHasherHashCall wrap *gomock.Call
type MockPassHasherHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPassHasherHashCall) Return(arg0 string, arg1 error) *MockPassHasherHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPassHasherHashCall) Do(f func(string) (string, error)) *MockPassHasherHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPassHasherHashCall) DoAndReturn(f func(string) (string, error)) *MockPassHasherHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTokenHasher is a mock of TokenHasher interface.
type MockTokenHasher struct {
	ctrl     *gomock.Controller
	recorder *MockTokenHasherMockRecorder
	isgomock struct{}
}

// MockTokenHasherMockRecorder is the mock recorder for MockTokenHasher.
type MockTokenHasherMockRecorder struct {
	mock *MockTokenHasher
}

// NewMockTokenHasher creates a new mock instance.
func NewMockTokenHasher(ctrl *gomock.Controller) *MockTokenHasher {
	mock := &MockTokenHasher{ctrl: ctrl}
	mock.recorder = &MockTokenHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenHasher) EXPECT() *MockTokenHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockTokenHasher) Hash(value string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", value)
	ret0, _ := ret[0].(string)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockTokenHasherMockRecorder) Hash(value any) *MockTokenHasherHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockTokenHasher)(nil).Hash), value)
	return &MockTokenHasherHashCall{Call: call}
}

// MockTokenHasherHashCall wrap *gomock.Call
type MockTokenHasherHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenHasherHashCall) Return(arg0 string) *MockTokenHasherHashCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenHasherHashCall) Do(f func(string) string) *MockTokenHasherHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenHasherHashCall) DoAndReturn(f func(string) string) *MockTokenHasherHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTxManager) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTxManagerMockRecorder) WithinTransaction(ctx, fn any) *MockTxManagerWithinTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTxManager)(nil).WithinTransaction), ctx, fn)
	return &MockTxManagerWithinTransactionCall{Call: call}
}

// MockTxManagerWithinTransactionCall wrap *gomock.Call
type MockTxManagerWithinTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxManagerWithinTransactionCall) Return(arg0 error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxManagerWithinTransactionCall) Do(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxManagerWithinTransactionCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MockTxManagerWithinTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
